# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7490482257b56fe480f6394b2884a6c59343c015c61cf33b8acb835890b1bc5a2f8cee071cc67115946e8b9c0dcb789dd2b0b5a81eff4fbbd597e6c8935b6ffb

test:
  secret_key_base: 5c1ec280793c23f15cb31150e796b37f71d85d7f7a3ac4db1d10caaed302c7c571bdf64259ebeaaccfee48498b59fd62fa87a713abc93754faa1282f0e5855bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
